version: 2.1
jobs:
  server:
    working_directory: ~/pyrog/server
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout:
          path: ~/pyrog
      - setup_remote_docker
      - run:
          name: Docker compose up pyrog server
          command: env $([ -f .env.dev.custom ] && cat .env.dev.custom || cat .env.dev.default) docker-compose up --build -d
      - run:
          name: Build and run docker container for server tests ; Update codecov results
          command: |
            docker build -f Dockerfile.test --network server_default -t arkhn/pyrog_server_test:latest .
            docker run --name server_test --network server_default arkhn/pyrog_server_test:latest
            docker cp server_test:/usr/src/app/coverage .
            bash <(curl -s https://codecov.io/bash) -F server
  client:
    working_directory: ~/pyrog/client
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout:
          path: ~/pyrog
      - setup_remote_docker
      - run:
          name: Build and run docker container for client tests ; Update codecov results
          command: |
            docker build -f Dockerfile.test -t arkhn/pyrog_client_test:latest .
            docker run --name client_test arkhn/pyrog_client_test:latest
            docker cp client_test:/usr/src/app/coverage .
            bash <(curl -s https://codecov.io/bash) -F client
workflows:
  version: 2.1
  testing_workflow:
    jobs:
      - server
      - client
