name: pyrog-client

on:
  push:
    paths:
      - "client/**"

jobs:
  build:
    name: Build Pyrog client
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: client/node_modules
          key: ${{ runner.os }}-${{ hashFiles('client/yarn.lock') }}

      - run: yarn --cwd ./client install
      - run: yarn --cwd ./client build
      # Some cleaning need to be done, see Issue #105
      # - run: yarn --cwd ./client lint

  publish:
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - id: metadata
        run: |
          IMAGE=arkhn/pyrog-client
          # Always tag with first 8 of sha
          TAGS="${IMAGE}:${GITHUB_SHA::8}"

          # Has this workflow been triggered by an app tag ?
          if [[ "${GITHUB_REF}" == refs/tags/app/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/app/}
            # Is the tag on master and does it follow numeric versioning ?
            if [[ "${{ github.event.base_ref }}" == refs/heads/master ]] && [[ "${VERSION}" =~ ^v[0-9]{1,3}(\.[0-9]{1,3}(\.[0-9]{1,3})?)?$ ]]; then
              TAGS="${TAGS},${IMAGE}:latest"
              VERSION="${VERSION#v}"
            fi
          # Has this workflow been triggered by a branch ?
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          fi
          if [[ ! -z "${VERSION}" ]]; then
            TAGS="${TAGS},${IMAGE}:${VERSION}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: client
          file: ./client/Dockerfile
          build-args: |
            VERSION_NAME=${{ steps.metadata.outputs.version }}
            VERSION_SHA=${GITHUB_SHA::8}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: |
            com.arkhn.image.title=pyrog-client
            com.arkhn.image.description=${{ github.event.repository.description }}
            com.arkhn.image.url=${{ github.event.repository.html_url }}
            com.arkhn.image.source=${{ github.event.repository.clone_url }}
            com.arkhn.image.version=${{ steps.metadata.outputs.version }}
            com.arkhn.image.created=${{ steps.metadata.outputs.created }}
            com.arkhn.image.revision=${{ github.sha }}
            com.arkhn.image.licenses=${{ github.event.repository.license.spdx_id }}